# Site settings
title: Espaço Telhas Rondon | Uberlândia
description: "Espaço Telhas Rondon"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo.svg

# Hero
hero:
    hero_img: header-espacotelha.jpg
    hero_title: Espaço Telhas Rondon
    hero_description: Soluções para Telhado

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 34-3306-0621 / 9 9966-0178
    email: thiagoroque@espacotelhasrondon.com.br
    address: Av. Rondon Pacheco, 3150, Santa Maria, Uberlândia-MG

# Opening hours
monday_friday: 8:00 – 18:00
saturday: 8:00 – 12:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Av. Rondon Pacheco, 3150, Santa Maria, Uberlândia-MG, Brasil
    address_details: img/logo-map.svg

# Social settings
facebook: http://facebook.com/espacotelhasrondon
instagram: http://instagram.com/espacotelhasrondon

# Footer
copyright: © 2015 Espaço Telhas Rondon - Todos os direitos reservados

